version: '3.8'

services:
  server:
    build: 
      context: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - waha

  waha:
    image: devlikeapro/waha:latest
    ports:
      - "5002:3000"
    volumes:
      - waha-data:/app/data
    environment:
      - WAHA_PORT=3000
      - WAHA_SESSION_NAME=default
      - WAHA_HTTP=true
      - TZ=America/Guatemala

volumes:
  waha-data: