version: '3.8'

services:
  waha:
    image: devlikeapro/waha
    container_name: waha
    ports:
      - "5002:5000"
      - "3000:3000"
    environment:
      BASE_URL: http://44.193.210.104:4000/api/chatbot/chat
      PUBLIC_URL: http://44.193.210.104:4000/
      PORT: 5000
      MEDIA_PATH: /app/public/files
    volumes:
      - waha-data:/app/data
      - ./media:/app/public/files

volumes:
  waha-data:


# comandos para levantar
#docker pull devlikeapro/waha:arm
#docker tag devlikeapro/waha:arm devlikeapro/waha
#docker-compose up -d
